---
- name: Build NGINX Docker image
  hosts: localhost
  become: true

  tasks:
    - name: Copy Dockerfile
      copy:
        src: /home/user/testcase/dockerfile
        dest: /temp/

    - name: Build Docker image
      command: docker build -t nginx-image /temp/

    - name: Run Docker container
      command: docker run -d -p 81:81 --name nginx-container nginx-image
